"""Record Level 2 v0.4 branch implementation without promoting the layout to final approval."""
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]

def replace(path,old,new):
    p=ROOT/path
    s=p.read_text()
    if old not in s:
        raise SystemExit(f'Expected text not found in {path}: {old[:100]!r}')
    p.write_text(s.replace(old,new,1))

# Design/lore: distinguish confirmed size, implemented review blockout, and still-proposed exact arrangement.
path=Path('docs/design-and-lore.md')
replace(path,
"**September 11 Level 2 design correction:** Greg confirmed that the current 18 × 18 m Level 2 blockout is too small and that the replacement must be at least twice as large in both length and width, making **36 × 36 m the minimum target footprint**. This supersedes the earlier instruction to keep the Listener level small. The detailed v0.4 arrangement is proposed on `design/level2-expanded-map-v04` in [the expanded layout plan](level2-expanded-layout-v04.md). The current v0.3 Unity scene/prefab remains the implemented asset until the larger blockout is built and validated.",
"**September 11 Level 2 design correction:** Greg confirmed that the current 18 × 18 m Level 2 blockout is too small and that the replacement must be at least twice as large in both length and width, making **36 × 36 m the minimum target footprint**. This supersedes the earlier instruction to keep the Listener level small. Branch `design/level2-expanded-map-v04` now contains an **implemented v0.4 review blockout** at that minimum footprint, generated as the existing Level 2 scene/prefab with the travel contract preserved. The exact v0.4 room proportions and obstacle placements remain proposed until the blockout is reviewed. `main` still contains v0.3. Source/box-route validation has passed on v0.4; Unity 2022.3.55f1, Photon and headset validation remain pending.")
replace(path,
"| 2026-09-11 | Expand Level 2 to at least twice the current v0.3 blockout's length and width. Since v0.3 is 18 × 18 m, the replacement target is at least 36 × 36 m. Do not treat the earlier “keep the proposed small layout” instruction as active. Preserve the noisy-repair loop, two repair escape routes, safe entry/qualified exit, bottom-right reward-room rule and established gate language while redesigning the larger space. | Confirmed size correction; v0.4 arrangement proposed on `design/level2-expanded-map-v04`; Unity scene/prefab implementation and validation pending. |",
"| 2026-09-11 | Expand Level 2 to at least twice the current v0.3 blockout's length and width. Since v0.3 is 18 × 18 m, the replacement target is at least 36 × 36 m. Do not treat the earlier “keep the proposed small layout” instruction as active. Preserve the noisy-repair loop, two repair escape routes, safe entry/qualified exit, bottom-right reward-room rule and established gate language while redesigning the larger space. | Confirmed size correction. V0.4 review geometry is implemented on `design/level2-expanded-map-v04` and passes generated-source/box-route checks; exact arrangement still proposed for review; Unity, Photon and headset validation pending. |")
replace(path,
"### Expanded v0.4 layout proposal\n\nThe September 11 correction sets **36 × 36 m as the minimum Level 2 footprint**. The branch design keeps the existing entry end where practical, expands mainly north/east, and proposes Test Hall A, Lower Service Hall, West Observation Wing, Conditioning Hall B, East Bypass, North Gallery, a larger Repair Lab, the qualified exit and a bottom-right reward room. This creates multiple connected loops instead of a single oversized room.\n\nThe proposed Repair Lab has one route into North Gallery and another toward the east/bypass side. Large partitions, acoustic baffles and service blocks break long views without creating extra safe rooms. The exact room bounds, obstacle locations, ceiling target and repair-door positions remain proposals until the enlarged Unity blockout is reviewed. See [Level 2 expanded layout v0.4](level2-expanded-layout-v04.md) for the planning grid and implementation checklist.",
"### Expanded v0.4 review blockout\n\nThe September 11 correction sets **36 × 36 m as the minimum Level 2 footprint**. Branch `design/level2-expanded-map-v04` now implements that review blockout in the normal Level 2 scene/prefab. It keeps the existing safe-entry end where practical and expands mainly north/east into Test Hall A, Lower Service Hall, West Observation Wing, Conditioning Hall B, East Bypass, North Gallery, a larger Repair Lab, the qualified exit and the bottom-right reward room. This creates multiple connected loops instead of a single oversized room.\n\nThe Repair Lab has one route into North Gallery and another into the East Bypass. Large partitions, acoustic baffles, service blocks and offset bypass walls break long views without creating extra safe rooms. Source-level geometry checks confirm the player proxy and conservative Listener proxy can reach the Repair Lab through either route when the other repair doorway is blocked. This is **implemented review geometry, not final layout approval**: exact room bounds, obstacle locations, the 5 m ceiling target and provisional repair-frame scaling remain proposed until Greg reviews the blockout in Unity/headset. See [Level 2 expanded layout v0.4](level2-expanded-layout-v04.md).")
marker="### Editable Level 2 blockout v0.3\n"
insert="""### Editable Level 2 blockout v0.4 — branch review prototype\n\n**Implemented on `design/level2-expanded-map-v04`:** the existing Level 2 scene path and reusable prefab are regenerated as `Level2_Blockout_v04` with a 36 × 36 m authored envelope, 5 m ceiling target, multiple connected chase spaces, two separated Repair Lab exits, retained Safe Entry/RETURN TO SECURITY wiring, the existing full exit gate family and bottom-right reward-room gate family. The v0.3 root was not uniformly scaled.\n\n**Source validated on the branch:** generated Unity object IDs are unique, local serialized references resolve, five linked gate instances remain present, required travel bindings remain serialized, human and conservative Listener proxies reach the gameplay spaces, either repair doorway can be blocked while the other route still reaches the Repair Lab, and the temporary exit/reward blockers isolate their spaces as intended. These checks exclude actual linked-gate bevel/collider clearance, NavMesh, animated Listener dimensions, Unity import/runtime, Photon and headset performance.\n\n**Pending validation:** Unity 2022.3.55f1 import/compile, both Runaway Chimps Editor validators, actual gate thresholds, Gorilla hand/body collision, 5 m scale judgment in headset, Listener turning/reach, NavMesh, safe-zone enforcement, repair pacing, travel, two-client Photon and Quest performance. `main` remains on v0.3 until this review branch is approved and merged.\n\n"""
p=ROOT/path; s=p.read_text()
if insert not in s:
    if marker not in s: raise SystemExit('v0.3 marker missing')
    p.write_text(s.replace(marker,insert+marker,1))
replace(path,
"Prototype with the hub, Level 1, and the Level 2 safe entry currently present in the merged v0.3 blockout while the expanded v0.4 map is designed.",
"For layout review, prototype with branch `design/level2-expanded-map-v04`; `main` still retains the merged v0.3 blockout until the enlarged geometry is approved and merged.")
replace(path,
"1. After the v0.4 layout arrangement is approved, rebuild the Level 2 scene/prefab and generator artifacts to the minimum 36 × 36 m target, then repeat Level 2 navigation, travel, collision, Photon and headset validation on the enlarged geometry.",
"1. Review the implemented v0.4 blockout's room proportions, route readability and pacing. After layout approval, tune/regenerate the geometry as needed, then complete Level 2 navigation, travel, collision, Photon and headset validation on the enlarged map.")

# Repository plan: implementation evidence and validation status.
path=Path('docs/repository-improvement-plan.md')
replace(path,
"**Current implementation evidence:** `Assets/RunawayChimps/Level2Blockout/Scenes/Level2_BehavioralConditioning_Blockout.unity`, its reusable prefab and `Tools/Level2Blockout/layout.json` still describe the 18 × 18 m v0.3 map on `main`. No expanded Unity geometry is implemented yet. Branch `design/level2-expanded-map-v04` records the correction and a proposed multi-space 36 × 36 m planning grid in [Level 2 expanded layout v0.4](level2-expanded-layout-v04.md). The exact room bounds, obstacle placements, ceiling target and repair-door positions remain **proposed**, not confirmed.",
"**Current implementation evidence:** `main` still contains the 18 × 18 m v0.3 map, but branch `design/level2-expanded-map-v04` now regenerates `Assets/RunawayChimps/Level2Blockout/Scenes/Level2_BehavioralConditioning_Blockout.unity`, its reusable prefab and `Tools/Level2Blockout/layout.json` as a **36 × 36 m v0.4 review blockout**. It preserves `Level2EntrySpawn`, RETURN TO SECURITY and the existing sector/travel bindings while adding Test Hall A, Lower Service Hall, West Observation, Conditioning Hall B, East Bypass, North Gallery and a larger Repair Lab. The exact room bounds, obstacle placements, 5 m ceiling target and provisional repair-frame scaling remain **proposed for review**, not final confirmed design.")
replace(path,
"**Required implementation after layout approval:** rebuild authored Level 2 geometry rather than scaling the v0.3 root transform to 2×. Update `Tools/Level2Blockout/layout.json`, its build/drawing tools, the reusable prefab and standalone scene together so they remain synchronized. Preserve the existing travel/sector components and safe-entry return control, re-place linked gates using the confirmed standards, then rebuild navigation and Listener routes after geometry stabilizes.",
"**Implemented on the review branch:** authored geometry was rebuilt rather than scaling the v0.3 root. `Tools/Level2Blockout/build_level2.py`, `layout.json`, the linked-gate placement, reusable prefab and standalone scene are synchronized for v0.4. The safe-entry travel/sector components and RETURN TO SECURITY control are preserved. Navigation and Listener runtime behavior remain pending until the physical layout is approved.")
replace(path,
"**Pending validation:** source validators; Unity 2022.3.55f1 import/compile; both Runaway Chimps Editor validators; safe-entry/exit and reward-room boundaries; actual framed-gate clearance; Listener turning through every common route; both repair-room escape loops; hand/body collision; travel markers; two-client Photon behavior; warning/audio pacing; Quest frame-time and memory. The v0.3 source checks do not validate v0.4 geometry.",
"**Source validation completed on v0.4:** generated scene/prefab IDs and local references resolve; five linked gate instances and required travel bindings remain present; a 0.35 m-radius / 2.0 m-height player proxy and conservative 1.375 m-radius / 3.2 m-height Listener proxy reach the gameplay spaces; either repair doorway can be blocked while the other route still reaches the Repair Lab; temporary exit/reward blockers isolate their spaces, and removing the reward blocker reconnects the player route. **Pending validation:** Unity 2022.3.55f1 import/compile; both Runaway Chimps Editor validators; actual framed-gate clearance; Gorilla hand/body collision; Listener animated turning/reach; NavMesh; safe-zone enforcement; travel markers; two-client Photon behavior; warning/audio pacing; Quest frame-time and memory.")

# Expanded-layout note: implementation is present but arrangement still awaits review.
path=Path('docs/level2-expanded-layout-v04.md')
replace(path,
"**Proposed:** the room arrangement and dimensions below. The existing v0.3 Unity scene remains the implemented map until a larger scene/prefab is built and validated.",
"**Implemented for review:** branch `design/level2-expanded-map-v04` now builds the room arrangement below into the normal Level 2 Unity scene and reusable prefab. The exact arrangement/dimensions remain **proposed for final design approval** until the blockout is reviewed. `main` still contains v0.3.")
replace(path,
"## Implementation after layout approval\n\n1. Rebuild the Level 2 blockout as v0.4 from authored geometry instead of scaling the old root.\n2. Update `Tools/Level2Blockout/layout.json`, its generator/drawing tools, the reusable prefab and the standalone scene together.\n3. Preserve existing travel components and RETURN TO SECURITY behavior; move markers only when the new geometry requires it.\n4. Re-place linked gates using the confirmed standards and measure actual mesh/collider clearance in Unity.\n5. Rebuild navigation after the physical layout is stable.\n6. Rerun source checks, both Runaway Chimps Editor validators, Unity 2022.3.55f1 compile/import, Play Mode travel, two-client Photon tests and headset checks.",
"## Branch implementation status\n\n1. **Implemented:** rebuild v0.4 from authored geometry instead of scaling the old root.\n2. **Implemented:** synchronize `layout.json`, generator, reusable prefab and standalone scene.\n3. **Implemented:** preserve existing travel components, `Level2EntrySpawn` and RETURN TO SECURITY behavior.\n4. **Implemented / pending Unity measurement:** re-place linked gates using the confirmed asset families; actual mesh/collider clearance still needs Unity inspection.\n5. **Pending:** rebuild NavMesh and Listener runtime navigation after layout approval.\n6. **Source validated / runtime pending:** generated source and box-route checks pass; Runaway Chimps Editor validators, Unity 2022.3.55f1 compile/import, Play Mode travel, two-client Photon and headset checks remain pending.")

print('Updated Level 2 v0.4 implementation status in maintained docs.')
