<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DefineConstants>DEVELOPMENT_BUILD</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Scripts/FacilityAnnouncements/*.cs" Link="Production/%(Filename)%(Extension)" />
    <Compile Include="../../Assets/Scripts/Travel/SectorPresence.cs" Link="Production/SectorPresence.cs" />
  </ItemGroup>
</Project>
