"""One-time application of locally reviewed edits; removed after publication."""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[2]
def blob(data):
    return hashlib.sha1(b'blob ' + str(len(data)).encode() + b'\0' + data).hexdigest()

CHANGES = [
    ('.github/workflows/primate-cognitive-validation.yml', '93dd452e72dda20fc38b6ed2ed7214037376ac28', 'f4845c77a0157ba0d34a065cfeb9770734437bcc', [
        (10, 10, '      - Tools/PrimateCognitiveAdapterHarness/**\n'),
        (11, 11, '      - docs/primate-cognitive-review-2026-09-30.md\n'),
        (21, 21, '      - Tools/PrimateCognitiveAdapterHarness/**\n'),
        (22, 22, '      - docs/primate-cognitive-review-2026-09-30.md\n'),
        (42, 42, '      - name: Run production adapters against managed diagnostics\n        run: dotnet run --project Tools/PrimateCognitiveAdapterHarness/PrimateCognitiveAdapterHarness.csproj --configuration Release\n'),
    ]),
    ('Assets/RunawayChimps/Toys/PrimateCognitive/Prefabs/PrimateCognitiveEvaluation.prefab', 'e6668aa070d69608f755cc6c86a34674ff8ececd', 'e55a8f2f57e90e929d6f0e184dfd6577d9316598', [
        (696, 697, '  m_LocalPosition: {x: 0, y: 0.95, z: -0.06}\n'),
    ]),
    ('Assets/Scripts/Toys/PrimateCognitive/CognitiveContactGate.cs', '1a1e7141ae328b3248eb289cdf12f2c6f1bae00c', 'dc20f2d8757f7906c68ab2cca05a822e03d08e11', [
        (70, 71, '        public void RequestSync(string nonce)\n        {\n            // Retransmit the outstanding challenge until a reply consumes it.\n            // Replacing it every retry starves peers whose RTT exceeds the retry\n            // interval. Election/room reset still establishes a fresh challenge.\n            if (string.IsNullOrEmpty(RequestNonce)) RequestNonce = nonce;\n        }\n'),
    ]),
    ('Tools/PrimateCognitive/build_assets.py', '5b64669debbf07b971324ae8291248e9f5852a18', '6e7260e9f40afabb4460a543a7fec8f880fad09c', [
        (266, 267, "    # Keep the upper caps below the display housing throughout their press stroke.\n    surface = p.node('Controls_AdjustHeightHere', root, (0, .95, -.06), tilt=30)\n"),
    ]),
    ('Tools/PrimateCognitive/validate_assets.py', '3fb342a73036d5bd839ba3302fa30bbf81dd843a', 'c686a8c950c30517116538e47a34b0875ea24609', [
        (44, 44, '\n\ndef inspect_cap_clearance(graph):\n    """Check authored cap cubes in full parent TRS, at rest and fully pressed."""\n    transforms = {d[\'m_GameObject\'][\'fileID\']: i for i, (k, d) in graph.items() if k in (4, 224)}\n    housing = next(i for i, (k, d) in graph.items() if k == 1 and d[\'m_Name\'] == \'DisplayHousing\')\n\n    def world_point(transform_id, point, moving=0, depth=0):\n        if not transform_id:\n            return point\n        data = graph[transform_id][1]\n        vx, vy, vz = (point[i] * data[\'m_LocalScale\'][a] for i, a in enumerate(\'xyz\'))\n        qx, qy, qz, qw = (data[\'m_LocalRotation\'][a] for a in \'xyzw\')\n        # Rotate v by the authored quaternion, then translate through each parent.\n        tx, ty, tz = 2 * (qy * vz - qz * vy), 2 * (qz * vx - qx * vz), 2 * (qx * vy - qy * vx)\n        position = data[\'m_LocalPosition\']\n        point = (vx + qw * tx + qy * tz - qz * ty + position[\'x\'],\n                 vy + qw * ty + qz * tx - qx * tz + position[\'y\'],\n                 vz + qw * tz + qx * ty - qy * tx + position[\'z\'] + (depth if transform_id == moving else 0))\n        return world_point(data[\'m_Father\'][\'fileID\'], point, moving, depth)\n\n    def heights(go, moving=0, depth=0):\n        return [world_point(transforms[go], (x, y, z), moving, depth)[1]\n                for x in (-.5, .5) for y in (-.5, .5) for z in (-.5, .5)]\n\n    bottom = min(heights(housing))\n    for kind, pad in graph.values():\n        if kind != 114 or pad[\'m_Script\'][\'guid\'] != script(\'CognitivePad\'):\n            continue\n        cap = graph[pad[\'capRenderer\'][\'fileID\']][1][\'m_GameObject\'][\'fileID\']\n        for depth in (0, pad[\'pressDepth\']):\n            top = max(heights(cap, pad[\'cap\'][\'fileID\'], depth))\n            check(top <= bottom - .005, \'Pad \' + str(pad[\'index\'] + 1) + \' cap intersects display housing or lacks 5 mm clearance\')\n'),
        (92, 92, '    inspect_cap_clearance(graph)\n'),
        (155, 155, "    broken = copy.deepcopy(graph)\n    deck_go = next(i for i, (k, d) in broken.items() if k == 1 and d['m_Name'] == 'Controls_AdjustHeightHere')\n    deck = next(d for k, d in broken.values() if k == 4 and d['m_GameObject']['fileID'] == deck_go)\n    deck['m_LocalPosition']['y'] = .98  # Original overlap regression.\n    mutants.append(broken)\n"),
        (163, 164, "    print('PASS: dimensions/labels; six PCM waveforms and four distinct pitches; rest/pressed cap clearance; five broken-asset mutations rejected.')\n"),
    ]),
    ('Tools/PrimateCognitiveHarness/Program.cs', 'a21989831bf586e8e82a69281c7542cae4cd7bb0', 'ede30ce183e1a663df69536389d5504c40c4bb66', [
        (195, 195, '    private static void DelayedHandshake()\n    {\n        // Retries every .5 seconds must not invalidate a .75+ second reply.\n        var replica = new CognitiveReplica();\n        var idle = new CognitiveGame().Snapshot();\n        replica.Elect(1, "initial-request");\n        string inFlight = replica.RequestNonce;\n        for (int retry = 0; retry < 20; retry++)\n            replica.RequestSync("retry-" + retry);\n        Check(replica.Accept(1, "current-term", inFlight, idle), "delayed initial reply survives retries");\n        Check(replica.RequestNonce == "", "accepted reply consumes outstanding request");\n        replica.RequestSync("restart-request");\n        inFlight = replica.RequestNonce;\n        replica.RequestSync("retry-after-restart");\n        Check(replica.Accept(1, "restarted-term", inFlight, idle), "delayed same-actor recovery survives retries");\n        Check(!replica.Accept(1, "current-term", inFlight, idle), "consumed nonce cannot revive old controller term");\n        replica.RequestSync("same-state");\n        Check(!replica.Accept(1, "restarted-term", "same-state", idle) && replica.RequestNonce == "",\n            "unchanged revision still acknowledges synchronization");\n        replica.RequestSync("before-election");\n        replica.Elect(2, "after-election");\n        Check(!replica.Accept(1, "restarted-term", "before-election", idle), "pending reply from departed controller rejected");\n        Check(replica.Accept(2, "new-controller", "after-election", idle), "new controller gets independent request");\n    }\n\n'),
        (197, 198, '        Sequences(); Recovery(); Contacts(); Protocol(); DelayedHandshake();\n'),
    ]),
    ('docs/design-and-lore.md', '25bbd664be676c2198a449014865c5f1df5db945', '236b6ceaf0783edee94cf2eac0d4e6b805a34508', [
        (15, 15, '\n### September 30 repeated code review - PR #77\n\n**Confirmed / implemented on the unmerged feature branch:** Greg requested repeated self-review and fixes until a pass found no further issues. Pass 1 reproduced a synchronization starvation defect: every retry replaced the outstanding nonce, so replies slower than the retry interval could never establish the replica. Retries now retain the challenge until a reply consumes it; room/election changes still replace it. Pass 2 found an actual intersection between the upper button caps and the display housing in the serialized transforms. The authored control deck moves from Y=0.98 m to Y=0.95 m, preserving dimensions, IDs and all references; an independent parent-transform calculation now requires 5 mm of vertical cap clearance at rest and full press.\n\n**Validated managed/source-data review:** the new delayed-handshake tests failed against the previous code; the clearance check failed against the previous prefab. After correction, 57,020 core assertions, 63 assertions across six production machine/pad adapter diagnostic groups, the five negative prefab mutations and four contact-filter mutations pass. The adapter harness uses explicit Unity/Photon doubles and manually delivered callbacks, not a live Photon session or Unity engine. The third full review found no further actionable issues within this source/managed/asset-data scope. [Review evidence](primate-cognitive-review-2026-09-30.md) records the passes and remaining acceptance; PR #77 records the final published revision and full-repository CI results.\n\n**Pending validation remains unchanged:** Unity 2022.3.62f3 import/compilation, native contact callbacks, Editor placement/Undo, actual rendering/audio, two-client networking and seated/standing headset acceptance still require execution. Do not treat a clean review pass or the new adapter diagnostic compilation as those passes.\n'),
    ]),
    ('docs/primate-cognitive-evaluation.md', 'ba90380363d3ee85cae7defdac9fd85d5b035b0d', '719690ad254628ea6e3bd33082c1b6bf3cbe2aa2', [
        (37, 39, '| Control deck | `Controls_AdjustHeightHere`: local Y=0.95 m, X tilt=30 degrees; move this group vertically for reach tuning |\n| Approximate cap-center heights | Main rows 0.87 m and 1.10 m; start 0.72 m above the floor pivot |\n'),
        (63, 64, 'Pacing settings are read when a new authority term/model is created; restart Play Mode after tuning them. The controller checks current-sector presence and deadlines. Walking away requests release; travel, disconnect, pause, component disable and missing heartbeats release/reset through the corresponding lifecycle or timeout path. Authority changes create a fresh idle model instead of trying to preserve a half-demonstrated round. Command numbering survives scene/component replacement; idle recovery clears stale command floors, and heartbeat/release commands also require the current session. Old sessions cannot release a newly restarted game. A fresh sync handshake recovers late arrivals or a restarted controller without replaying old audio. Retries reuse the outstanding nonce until an acknowledgement consumes it, so a response slower than the retry interval remains valid. Election and room changes create a new challenge.\n\n## Repeated code review, September 30\n\nThe [review record](primate-cognitive-review-2026-09-30.md) documents two reproduced defects and their fixes: delayed synchronization reply starvation and upper-cap/display-housing intersection. The control deck is now 3 cm lower. Asset validation requires at least 5 mm of vertical cap clearance at both rest and full depression. This is serialized geometry evidence, not a rendered/headset acceptance result.\n\nA new `Tools/PrimateCognitiveAdapterHarness` compiles the real machine, pad, rules, replica and sector-presence code against managed Unity/Photon doubles. It passes 63 assertions in six groups covering delayed initial/restarted-authority sync, physical/Editor inputs, collider identity and cleanup, room/pause/distance/disable lifecycle, operator/spectator isolation, stale releases, abandonment, authority handoff and malformed/unrelated events. These manually delivered callbacks do not test Unity scheduling, PhysX or actual Photon transport. Run it with `dotnet run --project Tools/PrimateCognitiveAdapterHarness/PrimateCognitiveAdapterHarness.csproj --configuration Release`.\n\nThe third review pass found no further actionable issues in the reviewed scope. Native Unity, Photon and headset acceptance remains pending, and the PR remains unmerged.\n'),
        (69, 70, 'The production rules/contact/replica harness passes **57,020 assertions** across 128 seeds and all sixteen rounds, including sequence extension, correct/wrong input, held/duplicate contact, state transitions, restart, completion, timeouts and controller-term replay. The existing card harness passes **18,015 assertions**. Asset checks inspect all local references and assigned material/font/clip identities, control dimensions, six bounded PCM waveforms and four distinct pitches; they reject five deliberately broken prefab mutations. Actual Bootstrap contact checks reject four filter mutations and verify both hand-child contacts, excluded grab spheres and the collision matrix. These remain data/managed/source checks, not native Unity tests.\n'),
    ]),
    ('docs/repository-improvement-plan.md', 'b91c3f1214fcd6b61810d726b77d76610cab7689', '76bcc0e339d92492163e12f8a872fd92ee1fda58', [
        (17, 17, '\n### September 30 repeated code review - PR #77\n\n**Confirmed / implemented on the unmerged feature branch:** Greg requested repeated self-review and fixes until a pass found no further issues. Pass 1 reproduced a synchronization starvation defect: every retry replaced the outstanding nonce, so replies slower than the retry interval could never establish the replica. Retries now retain the challenge until a reply consumes it; room/election changes still replace it. Pass 2 found an actual intersection between the upper button caps and the display housing in the serialized transforms. The authored control deck moves from Y=0.98 m to Y=0.95 m, preserving dimensions, IDs and all references; an independent parent-transform calculation now requires 5 mm of vertical cap clearance at rest and full press.\n\n**Validated managed/source-data review:** the new delayed-handshake tests failed against the previous code; the clearance check failed against the previous prefab. After correction, 57,020 core assertions, 63 assertions across six production machine/pad adapter diagnostic groups, the five negative prefab mutations and four contact-filter mutations pass. The adapter harness uses explicit Unity/Photon doubles and manually delivered callbacks, not a live Photon session or Unity engine. The third full review found no further actionable issues within this source/managed/asset-data scope. [Review evidence](primate-cognitive-review-2026-09-30.md) records the passes and remaining acceptance; PR #77 records the final published revision and full-repository CI results.\n\n**Pending validation remains unchanged:** Unity 2022.3.62f3 import/compilation, native contact callbacks, Editor placement/Undo, actual rendering/audio, two-client networking and seated/standing headset acceptance still require execution. Do not treat a clean review pass or the new adapter diagnostic compilation as those passes.\n'),
    ]),
 ]
for name, before, after, edits in CHANGES:
    path = ROOT / name
    data = path.read_bytes()
    assert blob(data) == before, 'Concurrent change or incorrect base: ' + name
    lines = data.decode('utf-8').splitlines(keepends=True)
    for start, end, replacement in reversed(edits):
        lines[start:end] = [replacement]
    updated = ''.join(lines).encode('utf-8')
    assert blob(updated) == after, 'Patch transcription mismatch: ' + name
    path.write_bytes(updated)
