#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

RECORDS = {
    "docs/launch-presentation.md": '''## September 14 correction — startup vignette vs. Hub spawn\n\n**Confirmed correction:** the security workstation is a **private, temporary loading presentation only**. It must never become the physical place where the player arrives in `Hub_Base`, and it must not remain visible in the Hub after startup. The intended transition is workstation/boot -> full black -> workstation/Loading presentation destroyed or unloaded -> local rig already placed at its real Hub spawn -> black fades up into the Hub. This supersedes the earlier absolute-world-stationary wording.\n\nDuring hidden startup relocation, the presentation should stay perceptually stable for the local user by following **XR-origin/root relocation** while remaining independent of head look/room-scale head motion. That lets `RigSpawnSnapper` move/rotate the persistent XR origin behind the loading presentation without leaving the desk behind. The workstation still disappears completely before Hub reveal.\n\n**Confirmed multiplayer requirement:** the shared Hub must not rely on one physical `HubSpawn` for all players. The current source still uses one Hub spawn marker, so unique multiplayer Hub placement is **pending implementation**. The intended design is a small set of authored Hub spawn slots (up to the current 10-player room cap) assigned after Photon room join and before the Hub is revealed. Players' startup workstations remain local-only and are never synchronized or mutually visible. Level-return routes continue using their route-specific arrival markers rather than the cold-start slot pool.''',

    "docs/launch-workstation-vignette.md": '''## September 14 correction — presentation-space anchoring and disappearance\n\n**Confirmed correction:** the workstation is not shared Hub geometry and must not survive into gameplay. It is a client-local loading set. Before `Hub_Base` becomes visible, the workstation must be completely covered by black and destroyed/unloaded; the user then fades up at the normal Hub spawn assigned to that client.\n\nThe prior wording that the workstation remains absolute-world-stationary is superseded. It should remain stationary relative to local head turning/room-scale motion, but it must track hidden **XROrigin root relocation** during startup so a later `RigSpawnSnapper` translation/rotation cannot move the user away from the desk while it is still being viewed.\n\n**Pending implementation from code review:** current `SecurityWorkstationVignette` captures a fixed world pose before `RigSpawnSnapper` necessarily finishes, and current startup uses one shared `HubSpawn`. Fix the vignette anchor and add unique multiplayer Hub spawn slots before treating the launch flow as merge-ready.''',

    "docs/design-and-lore.md": '''## September 14 launch vignette and multiplayer Hub-spawn correction\n\n**Confirmed correction:** the launch workstation is a private loading vignette, not a physical Hub workstation/arrival location. Each client sees only its own temporary desk/monitor presentation. Startup must end with an opaque black cover, removal/unload of that presentation, and then a reveal of the player at their actual Hub spawn. The workstation never persists into shared Hub gameplay.\n\nThe startup set may follow hidden `XROrigin` root relocation so the desk stays perceptually stable while the persistent rig is snapped behind black/loading presentation; it must not follow ordinary head look or become head-locked. This supersedes the earlier absolute-world-stationary interpretation that could leave the desk behind when the XR origin moves.\n\n**Confirmed multiplayer requirement:** simultaneous players should not all materialize at one `HubSpawn`. The Hub should provide distinct cold-start spawn slots for the current 10-player session cap. Slot assignment happens after Photon room join and before reveal; startup workstations are local-only and do not participate in network spawning. Existing route-specific Hub return markers remain separate from the cold-start slot pool. Exact allocation code/marker layout is pending implementation.''',

    "docs/repository-improvement-plan.md": '''## September 14 launch-vignette / Hub-spawn follow-up\n\n**Code-review finding / confirmed UX correction:** `SecurityWorkstationVignette` currently fixes its world pose as soon as the XR camera is available, while `RigSpawnSnapper` can later translate/rotate the whole `XROrigin`. That can move the player away from the desk during startup. The approved behavior is instead a local loading presentation that follows hidden XR-origin/root relocation (without following normal head look), then is fully blacked out and destroyed/unloaded before the Hub is revealed. Do not make the launch desk a persistent Hub object.\n\n**Multiplayer spawn gap:** current `RigSpawnSnapper` and the Photon player-spawn path ultimately use one `HubSpawn`, which is not acceptable for simultaneous cold starts in a room capped at 10 players. Add an authored Hub cold-start spawn-slot set and a synchronized allocation rule before reveal. Recommended direction: up to 10 clearly separated markers, allocate a free slot after Photon room join, publish/track the assignment so concurrent clients cannot choose the same slot, and release/reuse slots as players leave. Keep level-return/terminal arrival markers independent.\n\n**Implementation status:** decision confirmed; spawn-slot allocator and presentation-anchor correction are pending. The existing PR #21 source-validation success predates this correction and must not be treated as validation of the corrected behavior.'''
}

for relative, block in RECORDS.items():
    path = ROOT / relative
    current = path.read_text(encoding="utf-8-sig")
    heading = block.splitlines()[0]
    if heading not in current:
        path.write_text(current.rstrip() + "\n\n" + block.strip() + "\n", encoding="utf-8")
